import { type DB_MovieType } from "@/server/db/schema";

export const dummyMovies: DB_MovieType[] = [
  {
    id: "movie1",
    title: "Movie One",
    description: "Description for Movie One",
    quality: "HD",
    slug: "movie-one",
    genre: "Action",
    country: "USA",
    imdbRating: 7.5,
    duration: 120,
    releaseDate: new Date("2023-01-15"),
    platformReleaseDate: new Date("2023-02-15"),
    cast: "Actor A, Actor B",
    productionCompany: "Company X",
    season: null,
    episode: null,
    serieId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "movie2",
    title: "Movie Two",
    description: "Description for Movie Two",
    quality: "4K",
    slug: "movie-two",
    genre: "Comedy",
    country: "Canada",
    imdbRating: 8.0,
    duration: 95,
    releaseDate: new Date("2023-05-20"),
    platformReleaseDate: new Date("2023-06-01"),
    cast: "Actor C, Actor D",
    productionCompany: "Company Y",
    season: null,
    episode: null,
    serieId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie1_ep1",
    title: "Serie One: Episode 1",
    description: "Description for Serie One Episode 1",
    quality: "HD",
    slug: "serie-one-episode-1",
    genre: "Drama",
    country: "UK",
    imdbRating: 8.5,
    duration: 45,
    releaseDate: new Date("2023-09-10"),
    platformReleaseDate: new Date("2023-09-15"),
    cast: "Actor E, Actor F",
    productionCompany: "Company Z",
    season: "1",
    episode: 1,
    serieId: "serie1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie1_ep2",
    title: "Serie One: Episode 2",
    description: "Description for Serie One Episode 2",
    quality: "HD",
    slug: "serie-one-episode-2",
    genre: "Drama",
    country: "UK",
    imdbRating: 8.8,
    duration: 48,
    releaseDate: new Date("2023-09-17"),
    platformReleaseDate: new Date("2023-09-22"),
    cast: "Actor E, Actor F, Actor G",
    productionCompany: "Company Z",
    season: "1",
    episode: 2,
    serieId: "serie1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie1_ep3",
    title: "Serie One: Episode 3",
    description: "Description for Serie One Episode 3",
    quality: "HD",
    slug: "serie-one-episode-3",
    genre: "Drama",
    country: "UK",
    imdbRating: 9.0,
    duration: 50,
    releaseDate: new Date("2023-09-24"),
    platformReleaseDate: new Date("2023-09-29"),
    cast: "Actor E, Actor F",
    productionCompany: "Company Z",
    season: "1",
    episode: 3,
    serieId: "serie1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie2_ep1",
    title: "Serie Two: Episode 1",
    description: "Description for Serie Two Episode 1",
    quality: "HD",
    slug: "serie-two-episode-1",
    genre: "Comedy",
    country: "UK",
    imdbRating: 8.8,
    duration: 48,
    releaseDate: new Date("2023-09-17"),
    platformReleaseDate: new Date("2023-09-22"),
    cast: "Actor H, Actor I",
    productionCompany: "Company W",
    season: "1",
    episode: 1,
    serieId: "serie2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie1_ep4",
    title: "Serie Two: Episode 1",
    description: "Description for Serie Two Episode 1",
    quality: "HD",
    slug: "serie-two-episode-1",
    genre: "Comedy",
    country: "UK",
    imdbRating: 8.8,
    duration: 48,
    releaseDate: new Date("2023-09-17"),
    platformReleaseDate: new Date("2023-09-22"),
    cast: "Actor H, Actor I",
    productionCompany: "Company W",
    season: "1",
    episode: 4,
    serieId: "serie2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie1_ep5",
    title: "Serie Two: Episode 1",
    description: "Description for Serie Two Episode 1",
    quality: "HD",
    slug: "serie-two-episode-1",
    genre: "Comedy",
    country: "UK",
    imdbRating: 8.8,
    duration: 48,
    releaseDate: new Date("2023-09-17"),
    platformReleaseDate: new Date("2023-09-22"),
    cast: "Actor H, Actor I",
    productionCompany: "Company W",
    season: "1",
    episode: 5,
    serieId: "serie2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "serie2_ep2",
    title: "Serie Two: Episode 2",
    description: "Description for Serie Two Episode 2",
    quality: "HD",
    slug: "serie-two-episode-2",
    genre: "Comedy",
    country: "UK",
    imdbRating: 8.8,
    duration: 48,
    releaseDate: new Date("2023-09-17"),
    platformReleaseDate: new Date("2023-09-22"),
    cast: "Actor H, Actor I",
    productionCompany: "Company W",
    season: "2",
    episode: 2,
    serieId: "serie2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];